# Generated by Django 4.0.6 on 2023-01-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_aboutcontent_id_alter_academic_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='contactHeader',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='contactParagraph',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='message',
            field=models.TextField(default=None),
        ),
    ]
